### ISSUE TITLE
1.5 cant log in

### ISSUE THREAD

**Issue by satanKami** [teagan75/Witchery#33]
ive updated to 1.5 and now the game always crush...can't open it

**Comment by teagan75** [comment]
Version 1.5 has an updated level.dat which means you keeping your inventory and parts of the map won’t work from previous versions.

**Comment by satanKami** [comment]
im sorry i didnt cleared myself
i updated and press play and got the minecraft log in option to play...
every time i tried to play it ,it will crash

**Comment by teagan75** [comment]
Crash report?

**Comment by satanKami** [comment]
im not sure how to get the new crash report...but i think it's this-logs

[22:35:58] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[22:35:58] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[22:35:58] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[22:35:58] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[22:35:58] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 8:amd64:6.2, installed at D:\Games\MC\launcher\Curse\Install\runtime\jre-x64\1.8.0_25
[22:35:59] [main/WARN]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:35:59] [main/INFO]: Loading tweaker me.guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.0.1.jar
[22:35:59] [main/WARN]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:35:59] [main/INFO]: Loading tweaker fastcraft.Tweaker from fastcraft-1.23.jar
[22:35:59] [main/WARN]: The coremod com.endertech.minecraft.forge.coremod.DummyPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:35:59] [main/WARN]: The coremod lumien.hardcoredarkness.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:35:59] [main/WARN]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:35:59] [main/WARN]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:35:59] [main/WARN]: The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:35:59] [main/WARN]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:35:59] [main/WARN]: The coremod lumien.perfectspawn.Transformer.PSLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:35:59] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:35:59] [main/INFO]: Loading tweak class name me.guichaguri.betterfps.tweaker.BetterFpsTweaker
[22:35:59] [main/INFO]: Loading tweak class name fastcraft.Tweaker
[22:35:59] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[22:35:59] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:35:59] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:35:59] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:35:59] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[22:36:00] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Finished data injection.
[22:36:00] [main/INFO]: Finished data injection.
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class me.guichaguri.betterfps.tweaker.BetterFpsTweaker
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
[22:36:00] [main/INFO]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
[22:36:00] [main/INFO]: [ChunkCollisionTransformer] Hook registered for net.minecraft.item.ItemBlock
[22:36:00] [main/INFO]: [ChunkCollisionTransformer] Hook registered for net.minecraft.network.NetHandlerPlayServer
[22:36:00] [main/INFO]: [ChunkBlockTransformer] Hook registered for net.minecraft.world.chunk.Chunk
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:36:00] [main/INFO]: Calling tweak class fastcraft.Tweaker
[22:36:00] [main/INFO]: FastCraft loaded.
[22:36:00] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[22:36:00] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[22:36:00] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[22:36:00] [main/INFO]: Patching Game Start...
[22:36:00] [main/INFO]: TrashSlot will now patch func_147112_ai in bao...
[22:36:00] [main/INFO]: TrashSlot successfully patched func_147112_ai in bao!
[22:36:00] [main/INFO]: Found World Class: net/minecraft/world/World
[22:36:00] [main/INFO]:  - Patched minimal sky light (1)
[22:36:00] [main/INFO]:  - Patched minimal sky light (2)
[22:36:00] [main/INFO]: Found hooks for net.minecraft.world.World (ahb)
[22:36:00] [main/INFO]: Patching EntityPlayer Class
[22:36:00] [main/INFO]: - Patched Staying in Bed Check
[22:36:00] [main/INFO]: Transforming Class: net.minecraft.entity.EntityLivingBase
[22:36:00] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayer
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 6 more
Caused by: java.lang.RuntimeException: EntityPlayer.getItemInUseDuration: no replacements made
	at squeek.applecore.asm.module.ModuleFoodEatingSpeed.patchGetItemInUseDuration(ModuleFoodEatingSpeed.java:110) ~[AppleCore-mc1.7.10-3.0.0.jar:?]
	at squeek.applecore.asm.module.ModuleFoodEatingSpeed.transform(ModuleFoodEatingSpeed.java:50) ~[AppleCore-mc1.7.10-3.0.0.jar:?]
	at squeek.applecore.asm.TransformerModuleHandler.transform(TransformerModuleHandler.java:41) ~[AppleCore-mc1.7.10-3.0.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 6 more
[22:36:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[22:36:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[22:36:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[22:36:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Runtime.exit(Runtime.java:107)
[22:36:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.System.exit(System.java:968)
[22:36:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[22:36:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by teagan75** [comment]
It has something to do with Apple core. I did update that mod. I haven’t heard if others are experiencing this same crash. 

You didn’t transfer your inventory over using mcedit like before?

**Comment by satanKami** [comment]
well to transfer i need to first open a world in 1.5 ^_^
well ill play with it now that i know the problem..

**Comment by satanKami** [comment]
well look like AppleCore-mc1.7.10-3.1.0 did transfer in the old version but AppleCore-mc1.7.10-3.1.0
did not moved into my new version... i guess it's was a curse download problem
yay teagan doesn't need to fix it!!

**Comment by satanKami** [comment]
so close
